### PR TITLE
Visual testing using cypress-plugin-snapshots

### LINKED ISSUE #4: Use Visual Testing
Implement [Visual Testing in Cypress](https://docs.cypress.io/guides/tooling/visual-testing.html) using the [cypress-plugin-snapshots](https://github.com/meinaart/cypress-plugin-snapshots).

**Acceptance Criteria**
Provide a way of Visual Testing where screenshots of the pages or elements are compared to previous baselines.

### PR DESCRIPTION
**Pull request by TAnas0**
## What is the Purpose?
Support visual testing

## What was the approach?
Followed the steps described in the issue and incorporated visual tests into the already existing tests.
Also generated baseline snapshots.

## Are there any concerns to addressed further before or after merging this PR?
Would like to make sure that the tests are passing in someone else's machine before merging.

There is room for improvement since Cypress offers multiple Visual Testing plugins: https://docs.cypress.io/plugins/#visual-testing

## Mentions
@sannleen 

## Issue(s) affected?
#4

### CODE REVIEW

**Comment by amosnjoroge** [comment]
Hi @TAnas0 Thanks for suggesting we include visual testing. However , I am of the view that since Activity is being developed under an MVP environment its UI will change frequently and with visual test assertions included test may fail not necessarily because the functionality under test is broken but may be due to unrelated UI changes. For example one of registration base images you included for the this test is (from https://activity-staging.hikaya.app)
image
however, since we are changing domains the new registration UI on https://activity-dev.hikaya.dev looks likes this (The large logo is removed)
image
This therefore would lead to failure of this test even through when we run the registration functionality on it, it would pass on both deployments.
My suggestion would we continue writing functionality tests and then after the MVP, and when we have a stable product, we improve the tests by adding visual tests as well.
cc @andrewtpham @odenypeter

**Comment by andrewtpham** [comment]
@sannleen can we try to include visual testing now but only use it for stable features? I believe Activity is getting to a stable place now so Im happy if we start to improve our testing across the entire app. Features considered stable now are:
- Login registration (that image change was a fluke but we should change things like that much more)
- Indicators
- Organization settings

**Comment by TAnas0** [comment]
@sannleen 
That's partly the point of Visual Testing, is our tests will fail and then we can manually review the change.
We can also select specific components for Visual Testing, such as this [dropdown](https://github.com/hikaya-io/cypress-tests-activity/blob/f975277fa03b3a9c8b6ccc1087bc740947ba2738/cypress/integration/sanity/__image_snapshots__/Registration%20%20ACTATC-1.2%20Create%20a%20New%20Organization%20%231.png)

**Comment by amosnjoroge** [comment]
Sure @andrewtpham. Thanks @TAnas0

**Pull request merged**
